language: go

go:
  - "1.11.x"
  - "1.12.x"

os:
  - linux
  - osx

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - golangci-lint run
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - go install
  - mkdir hugo && cd hugo && wget https://raw.githubusercontent.com/gohugoio/hugo/v0.53/go.mod
  - travis_wait env GO111MODULE=on go list -u -m -json all | go-mod-outdated
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
