--- 
services:
  - docker
go: 
  - 1.11.x
  - 1.12.x
jobs: 
  include: 
    - 
      after_success: 
        - "bash <(curl -s https://codecov.io/bash)"
      before_script: 
        - "curl sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0"
      script: 
        - "golangci-lint run"
        - "go test ./... -race -coverprofile=coverage.txt -covermode=atomic"
        - "go install"
        - "mkdir hugo && cd hugo && wget https://raw.githubusercontent.com/gohugoio/hugo/v0.53/go.mod"
        - "env GO111MODULE=on go list -u -m -json all | go-mod-outdated"
      stage: "run script"
    - 
      script: 
        - "docker build -t psampaz/go-mod-outdated ."
        - "docker run --rm --name some-name -v $(pwd):/home/project psampaz/go-mod-outdated"
      stage: "build docker image"
language: go
os: 
  - linux
  - osx
